# fly.toml app configuration file generated for solitary-mountain-5684 on 2023-10-09T10:10:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "solitary-mountain-5684"
primary_region = "ewr"

[build]

[env]
  PORT = "3001" # add this

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
